# Deployment Configuration - Prod Environment

# Mattermost Server
MM_HOST: 'mattermost-csc510-9.herokuapp.com'
MM_GROUP: 'alfred'
BOT_HANDLE: '@alfred'

# Google Drive
DRIVE_VERSION: 'v3'
SCOPES: 
    - 'https://www.googleapis.com/auth/drive'
    - 'https://www.googleapis.com/auth/drive.file'

# Token Server
TS_PORT: 7065
TS_REDIRECT_URI: 'https://mattermost-csc510-9.herokuapp.com/alfred/channels/'
TS_REDIRECT_INDEX: 0