# Deployment Configuration - Test Environment

# Mattermost Server
MM_HOST: 'mattermost-csc510-9-test.herokuapp.com'
MM_GROUP: 'alfredtest'
BOT_HANDLE: '@alfred'

# Google Drive
DRIVE_VERSION: 'v3'
SCOPES: 
    - 'https://www.googleapis.com/auth/drive'
    - 'https://www.googleapis.com/auth/drive.file'

# Token Server
TS_PORT: 7066
TS_REDIRECT_URI: 'https://mattermost-csc510-9-test.herokuapp.com/alfredtest/channels/'
TS_REDIRECT_INDEX: 1