- hosts: localhost
  become: yes

  vars:
    nodejs_version: "12"
    ubuntu_distribution: "xenial"
    app_url: "https://{{githubuser}}:{{githubpassword | urlencode}}@github.ncsu.edu/csc510-fall2019/CSC510-9.git"
    app_path: "/home/apateri/Alfred/CSC510-9"
  
  pre_tasks:
    - name: Retrieving the gpg key for nodejs LTS Xenial distribution
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    
    - name: Fetching the nodejs LTS repositories
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{nodejs_version}}.x {{ubuntu_distribution}} main"
        state: present

  tasks: 
    - name: Installing node.js
      apt:
        name: nodejs
        state: present
    
    - name: Installing package forever
      npm:
        name: forever
        state: present
        global: true

    - name: Cloning repository CSC510-9
      git:
        repo: "{{app_url}}"
        dest: "{{app_path}}"
        clone: yes
      become_user: apateri

    - name: Importing client secrets
      shell: cp secrets/credentials.json "{{app_path}}"/credentials.json

    - name: Installing node modules for CSC510-9
      shell: cd "{{app_path}}" && npm ci
      become_user: apateri
